name: app_tutorial_heyteacher
description: Package for creating onboarding flows for your app to explain the features of the app in a seamless ways to you users (fork by [Hey, Teacher](https://github.com/heyteacher)).
version: 1.0.8
repository: https://github.com/heyteacher/app_tutorial_heyteacher
license: BSD 3-Clause
issue_tracker: https://github.com/heyteacher/app_tutorial_heyteacher/issues
homepage: https://github.com/heyteacher/app_tutorial_heyteacher
documentation: https://github.com/heyteacher/app_tutorial_heyteacher
topics: [flutter, tutorial]

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0
